spring.application.name=backend

# Настройки подключения к локальной базе данных PostgreSQL
# название базы
spring.datasource.url=jdbc:postgresql://localhost:5432/planfood_db

# Укажи свой логин и пароль от PostgreSQL
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки генерации таблиц (Hibernate)
# Режим update заставляет Spring при запуске автоматически создать все таблицы (User, Recipe и т.д.)
spring.jpa.hibernate.ddl-auto=update

# Вывод логов в консоль idea
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true